# Generated by Django 6.0.6 on 2026-06-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
