# Generated by Django 6.0.6 on 2026-06-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_player_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
