# Generated by Django 6.0.6 on 2026-06-09 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=40, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email_address_for_login', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LevelOrPreset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level_or_preset', models.BooleanField()),
                ('visible_name', models.CharField(max_length=15, null=True)),
                ('enabled', models.BooleanField()),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Player_Playthrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_of_player_datetime', models.DateTimeField(null=True)),
                ('virt_time_in_game', models.PositiveIntegerField()),
                ('real_time_in_game', models.DurationField()),
                ('registered_actions_count', models.PositiveIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playthrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(null=True)),
                ('game_state', models.JSONField()),
                ('level', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playthrough', to='main.levelorpreset')),
                ('players', models.ManyToManyField(related_name='playthroughs', through='main.Player_Playthrough', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='player_playthrough',
            name='playthrough',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.playthrough'),
        ),
        migrations.CreateModel(
            name='GameAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virt_time_in_game', models.PositiveIntegerField()),
                ('action_type', models.PositiveSmallIntegerField()),
                ('par1', models.PositiveSmallIntegerField()),
                ('par2', models.PositiveSmallIntegerField()),
                ('player', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_action', to=settings.AUTH_USER_MODEL)),
                ('playthrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_actions', to='main.playthrough')),
            ],
        ),
    ]
